/*
===============================================================================
PROJECT: Retail Sales & Profitability Analysis
DATABASE: PostgreSQL
DATASET: Tableau Sample Superstore

OBJECTIVE:
Analyze retail sales and profitability to identify performance trends,
underperforming categories and subcategories, high-revenue products,
and the relationship between discount levels and profitability.

The analysis also identifies areas that may require further investigation.

NOTE:
Each row in the Superstore dataset represents an order line rather than
a unique customer order.
===============================================================================
*/



-- DATA SETUP

CREATE TABLE public.Superstore (
    Row_id INT,
    Order_id VARCHAR,
    Order_date DATE,
    Ship_Date DATE,
    Ship_Mode VARCHAR,
    Customer_id VARCHAR,
    Customer_Name TEXT,
    Segment TEXT,
    Country TEXT,
    City TEXT,
    State TEXT,
    Postal_Code VARCHAR,
    Region TEXT,
    Product_id VARCHAR,
    Category TEXT,
    Sub_Category TEXT,
    Product_Name VARCHAR,
    Sales NUMERIC,
    Quantity INT,
    Discount NUMERIC,
    Profit NUMERIC
);


-- DATA VALIDATION
-- These queries were used after importing the dataset.


-- Confirm total number of order-line records.
SELECT COUNT(*) AS Total_Order_Lines
FROM Superstore;


-- Confirm the number of unique customer orders.
SELECT COUNT(DISTINCT Order_id) AS Unique_Orders
FROM Superstore;



-- 1. OVERALL BUSINESS KPIs
-- Business Question:
-- What is the company's overall sales and profitability performance?

SELECT
    COUNT(DISTINCT Order_id) AS Unique_Orders,
    SUM(Quantity) AS Total_Quantity,
    ROUND(SUM(Sales), 2) AS Total_Sales,
    ROUND(SUM(Profit), 2) AS Total_Profit,
    ROUND(SUM(Profit) / SUM(Sales) * 100, 2) AS Profit_Margin_Pct,
    ROUND(SUM(Sales) / COUNT(DISTINCT Order_id), 2) AS Average_Order_Value
FROM Superstore;

/*
Key Result:
- 5,009 unique orders
- 37,873 units sold
- Approximately $2.30M in sales
- Approximately $286K in profit
- Overall profit margin approximately 12.47%
- Average order value approximately $458.61
*/



-- 2. CATEGORY PERFORMANCE
-- Business Question:
-- Which product categories generate the most sales and profit?

SELECT
    Category,
    ROUND(SUM(Sales), 2) AS Total_Sales,
    ROUND(SUM(Profit), 2) AS Total_Profit,
    ROUND(SUM(Profit) / SUM(Sales) * 100, 2) AS Profit_Margin_Pct
FROM Superstore
GROUP BY Category
ORDER BY Total_Sales DESC;

/*
Key Finding:
Furniture generated approximately $742K in sales but only $18.5K in profit,
resulting in a profit margin of approximately 2.49%.

This was substantially below the approximately 17% margins generated by
Technology and Office Supplies.
*/



-- 3. FURNITURE SUBCATEGORY PROFITABILITY
-- Business Question:
-- Which Furniture subcategories are contributing to weak profitability?

SELECT
    Sub_Category,
    ROUND(SUM(Sales), 2) AS Total_Sales,
    ROUND(SUM(Profit), 2) AS Total_Profit,
    ROUND(SUM(Profit) / SUM(Sales) * 100, 2) AS Profit_Margin_Pct
FROM Superstore
WHERE Category = 'Furniture'
GROUP BY Sub_Category
ORDER BY Total_Profit ASC;

/*
Key Finding:
Tables generated approximately $207K in sales but lost approximately $17.7K,
while Bookcases generated approximately $115K in sales and lost approximately
$3.5K.

Chairs and Furnishings remained profitable, indicating that Furniture's weak
performance was concentrated in specific subcategories rather than across
the entire category.
*/



-- 4. TABLES PROFITABILITY BY DISCOUNT
-- Business Question:
-- How does profitability within Tables vary across discount levels?

SELECT
    Discount,
    ROUND(SUM(Sales), 2) AS Total_Sales,
    ROUND(SUM(Profit), 2) AS Total_Profit,
    ROUND(SUM(Profit) / SUM(Sales) * 100, 2) AS Profit_Margin_Pct,
    COUNT(*) AS Order_Lines
FROM Superstore
WHERE Category = 'Furniture'
  AND Sub_Category = 'Tables'
GROUP BY Discount
ORDER BY Discount ASC;

/*
Purpose:
After identifying Tables as the largest loss-making Furniture subcategory,
this query drills further into its performance across discount levels.

Interpretation should consider transaction volume at each discount level,
since some discount levels contain relatively few observations.
*/



-- 5. PROFITABILITY BY DISCOUNT GROUP
-- Business Question:
-- How does profitability vary across different discount levels?
--
-- NOTE:
-- These discount bands are analyst-defined for exploratory analysis and do
-- not represent official company discount policies.

SELECT
    CASE
        WHEN Discount = 0 THEN 'No Discount'
        WHEN Discount <= 0.20 THEN 'Low Discount'
        WHEN Discount <= 0.40 THEN 'Medium Discount'
        ELSE 'High Discount'
    END AS Discount_Group,
    ROUND(SUM(Sales), 2) AS Total_Sales,
    ROUND(SUM(Profit), 2) AS Total_Profit,
    ROUND(SUM(Profit) / SUM(Sales) * 100, 2) AS Profit_Margin_Pct,
    COUNT(*) AS Order_Lines
FROM Superstore
GROUP BY
    CASE
        WHEN Discount = 0 THEN 'No Discount'
        WHEN Discount <= 0.20 THEN 'Low Discount'
        WHEN Discount <= 0.40 THEN 'Medium Discount'
        ELSE 'High Discount'
    END
ORDER BY
    CASE
        WHEN Discount = 0 THEN 1
        WHEN Discount <= 0.20 THEN 2
        WHEN Discount <= 0.40 THEN 3
        ELSE 4
    END;

/*
Key Finding:
No Discount:      approximately 29.5% margin
Low Discount:     approximately 11.9% margin
Medium Discount: approximately -15.3% margin
High Discount:   approximately -77.4% margin

Higher discount bands were associated with substantially weaker profitability.

This relationship should not be interpreted as proof that discounting alone
caused the losses. Product mix, pricing, costs, and other factors may also
contribute.
*/



-- 6. ANNUAL BUSINESS PERFORMANCE
-- Business Question:
-- How did sales and profitability change from year to year?

SELECT
    EXTRACT(YEAR FROM Order_date) AS Year,
    ROUND(SUM(Sales), 2) AS Total_Sales,
    ROUND(SUM(Profit), 2) AS Total_Profit,
    ROUND(SUM(Profit) / SUM(Sales) * 100, 2) AS Profit_Margin_Pct,
    COUNT(DISTINCT Order_id) AS Unique_Orders
FROM Superstore
GROUP BY EXTRACT(YEAR FROM Order_date)
ORDER BY Year ASC;

/*
Key Finding:
2017 recorded the highest annual sales and profit in the dataset.

However, overall profit margin decreased slightly from approximately
13.43% in 2016 to 12.74% in 2017.
*/



-- 7. YEAR-OVER-YEAR SALES AND PROFIT GROWTH
-- Business Question:
-- How quickly did sales and profit grow compared with the previous year?
--
-- Skills Demonstrated:
-- CTEs, LAG(), window functions, year-over-year calculations

WITH Annual_Performance AS (
    SELECT
        EXTRACT(YEAR FROM Order_date) AS Year,
        SUM(Sales) AS Current_Year_Sales,
        SUM(Profit) AS Current_Year_Profit,
        SUM(Profit) / SUM(Sales) * 100 AS Profit_Margin_Pct
    FROM Superstore
    GROUP BY EXTRACT(YEAR FROM Order_date)
),

Performance_With_Previous_Year AS (
    SELECT
        Year,
        Current_Year_Sales,
        LAG(Current_Year_Sales) OVER (
            ORDER BY Year
        ) AS Previous_Year_Sales,
        Current_Year_Profit,
        LAG(Current_Year_Profit) OVER (
            ORDER BY Year
        ) AS Previous_Year_Profit,
        Profit_Margin_Pct
    FROM Annual_Performance
)

SELECT
    Year,
    ROUND(Current_Year_Sales, 2) AS Current_Year_Sales,
    ROUND(Previous_Year_Sales, 2) AS Previous_Year_Sales,

    ROUND(
        (Current_Year_Sales - Previous_Year_Sales)
        / NULLIF(Previous_Year_Sales, 0) * 100,
        2
    ) AS YoY_Sales_Growth_Pct,

    ROUND(Current_Year_Profit, 2) AS Current_Year_Profit,
    ROUND(Previous_Year_Profit, 2) AS Previous_Year_Profit,

    ROUND(
        (Current_Year_Profit - Previous_Year_Profit)
        / NULLIF(Previous_Year_Profit, 0) * 100,
        2
    ) AS YoY_Profit_Growth_Pct,

    ROUND(Profit_Margin_Pct, 2) AS Profit_Margin_Pct

FROM Performance_With_Previous_Year
ORDER BY Year;

/*
Key Findings:
Sales Growth:
2015: -2.83%
2016: +29.47%
2017: +20.36%

Profit Growth:
2015: +24.37%
2016: +32.74%
2017: +14.24%

From 2016 to 2017, sales grew approximately 20.4% while profit grew only
14.2%. Profit therefore grew more slowly than revenue, contributing to the
decline in overall profit margin.

NULLIF() is used to protect the growth calculation against division by zero.
*/



-- 8. TOP 3 PRODUCTS BY SALES WITHIN EACH CATEGORY
-- Business Question:
-- Which products generate the most sales within each product category?
--
-- Skills Demonstrated:
-- CTE, RANK(), PARTITION BY

WITH Product_Rankings AS (
    SELECT
        Category,
        Product_Name,
        SUM(Sales) AS Total_Sales,
        RANK() OVER (
            PARTITION BY Category
            ORDER BY SUM(Sales) DESC
        ) AS Sales_Rank
    FROM Superstore
    GROUP BY Category, Product_Name
)

SELECT
    Category,
    Product_Name,
    ROUND(Total_Sales, 2) AS Total_Sales,
    Sales_Rank
FROM Product_Rankings
WHERE Sales_Rank <= 3
ORDER BY Category, Sales_Rank, Product_Name;

/*
Purpose:
This query identifies the highest-revenue products within each category
rather than ranking products across the company as a whole.

RANK() allows tied products to receive the same ranking.
*/



-- 9. REGIONAL PERFORMANCE USING A JOIN
--
-- NOTE:
-- The Region_Managers table below is SYNTHETIC and was created solely to
-- demonstrate relational JOIN operations. The manager names are not part
-- of the original Tableau Sample Superstore dataset.


CREATE TABLE Region_Managers (
    Region VARCHAR(20),
    Regional_Manager VARCHAR(100)
);

INSERT INTO Region_Managers (Region, Regional_Manager)
VALUES
    ('Central', 'Jordan Lee'),
    ('East', 'Maya Patel'),
    ('South', 'Daniel Brooks'),
    ('West', 'Sofia Ramirez');


-- Business Question:
-- How much sales and profit is associated with each region?

SELECT
    s.Region,
    rm.Regional_Manager,
    ROUND(SUM(s.Sales), 2) AS Total_Sales,
    ROUND(SUM(s.Profit), 2) AS Total_Profit,
    ROUND(SUM(s.Profit) / SUM(s.Sales) * 100, 2) AS Profit_Margin_Pct
FROM Superstore AS s
LEFT JOIN Region_Managers AS rm
    ON s.Region = rm.Region
GROUP BY s.Region, rm.Regional_Manager
ORDER BY Total_Sales DESC;

/*
Skills Demonstrated:
LEFT JOIN, aliases, aggregation, GROUP BY.

Because the manager lookup is synthetic, conclusions from this query should
be interpreted as regional performance rather than actual employee
performance.
*/



-- 10. HIGH-REVENUE SUBCATEGORY PROFITABILITY
-- Business Question:
-- Which subcategories generated more than $100,000 in sales, and how
-- profitable were they?
--
-- Skills Demonstrated:
-- GROUP BY, HAVING, COUNT(DISTINCT), calculated profit margin

SELECT
    Sub_Category,
    ROUND(SUM(Sales), 2) AS Total_Sales,
    ROUND(SUM(Profit), 2) AS Total_Profit,
    ROUND(SUM(Profit) / SUM(Sales) * 100, 2) AS Profit_Margin_Pct,
    COUNT(DISTINCT Order_id) AS Unique_Orders
FROM Superstore
GROUP BY Sub_Category
HAVING SUM(Sales) > 100000
ORDER BY Total_Sales DESC;

/*
Key Finding:
High revenue did not consistently translate into strong profitability.

For example:
- Copiers generated approximately $150K in sales with a margin of ~37.2%.
- Tables generated approximately $207K in sales but had a negative margin.
- Bookcases generated more than $100K in sales but were also loss-making.
- Machines generated approximately $189K in sales with a margin of only ~1.8%.

This suggests that revenue alone is insufficient for evaluating product
performance.
*/


-- END OF ANALYSIS